## SEASON dataframe & EDA

In [1]:
#import necessary packages
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn
import re
import csv
from datetime import datetime
import os
import time
import dask
import json
import pickle

In [2]:
#opening pickle files
with open ('EVENT.PKL', 'rb') as f:
    event_df= pickle.load(f)

In [3]:
with open ('HOMERUNS.PKL', 'rb') as f:
    homeruns_df= pickle.load(f)

In [4]:
with open ('OFFENSE.PKL', 'rb') as f:
    offense_df= pickle.load(f)

In [5]:
with open ('STANDINGS.PKL', 'rb') as f:
    standings_df= pickle.load(f)

In [6]:
with open ('target_df.PKL', 'rb') as f:
    target_df= pickle.load(f)

In [7]:
# event_df.gameDate=[x.replace(x[-10:], '', len(event_df.gameDate)) for x in event_df.gameTimeUTC]

AttributeError: 'DataFrame' object has no attribute 'gameTimeUTC'

In [8]:
# event_df.drop(['gameTimeUTC'], axis=1, inplace=True)

In [12]:
event_df

           gameDate                 event
0        2018-03-29                  Balk
1        2018-03-29                Injury
2        2018-03-29              Ejection
3        2018-03-29            Pickoff 1B
4        2018-03-29            Runner Out
...             ...                   ...
2017781  2021-04-30      Grounded Into DP
2017782  2021-04-30      Grounded Into DP
2017783  2021-04-30      Grounded Into DP
2017784  2021-04-30      Grounded Into DP
2017785  2021-04-30  Sac Bunt Double Play

[622068 rows x 2 columns]

In [13]:
homeruns_df

          gameDate playerId      playerName  homeRuns       date
67      2018-03-29   607680    Kevin Pillar       1.0 2018-03-29
70      2018-03-29   443558     Nelson Cruz       1.0 2018-03-29
79      2018-03-29   518934     DJ LeMahieu       1.0 2018-03-29
94      2018-03-29   446263      Lucas Duda       1.0 2018-03-29
99      2018-03-29   605412       Joe Panik       1.0 2018-03-29
...            ...      ...             ...       ...        ...
185534  2021-04-30   571745   Mitch Haniger       1.0 2021-04-30
185535  2021-04-30   666182     Bo Bichette       1.0 2021-04-30
185537  2021-04-30   545341  Randal Grichuk       1.0 2021-04-30
185543  2021-04-30   543305     Aaron Hicks       1.0 2021-04-30
185552  2021-04-30   608324    Alex Bregman       1.0 2021-04-30

[14840 rows x 5 columns]

In [14]:
df=pd.read_csv('mlb-player-digital-engagement-forecasting/players.csv')

In [15]:
df

,playerId,playerName,DOB,mlbDebutDate,birthCity,birthStateProvince,birthCountry,heightInches,weight,primaryPositionCode,primaryPositionName,playerForTestSetAndFuturePreds
0,665482,Gilberto Celestino,1999-02-13,2021-06-02,Santo Domingo,NaN,Dominican Republic,72,170,8,Outfielder,False
1,593590,Webster Rivas,1990-08-08,2021-05-28,Nagua,NaN,Dominican Republic,73,219,3,First Base,True
2,661269,Vladimir Gutierrez,1995-09-18,2021-05-28,Havana,NaN,Cuba,73,190,1,Pitcher,True
3,669212,Eli Morgan,1996-05-13,2021-05-28,Rancho Palos Verdes,CA,USA,70,190,1,Pitcher,True
4,666201,Alek Manoah,1998-01-09,2021-05-27,Homestead,FL,USA,78,260,1,Pitcher,True
...,...,...,...,...,...,...,...,...,...,...,...,...
2056,672695,Geraldo Perdomo,1999-10-22,NaN,Santo Domingo,NaN,Dominican Republic,74,203,6,Shortstop,True
2057,672911,Jesus Cruz,1995-04-15,NaN,Salinas de Hidalgo,San Luis Potosi,Mexico,73,230,1,Pitcher,False
2058,676103,Damon Jones,1994-09-30,NaN,Twin Falls,ID,USA,77,233,1,Pitcher,True
2059,676755,Isaac Mattson,1995-07-14,NaN,Erie,PA,USA,74,205,1,Pitcher,True
2060,680430,Nick Allgeyer,1996-02-03,NaN,St. Louis,MO,USA,75,210,1,Pitcher,True

In [16]:
#creating a dictionary for player Id: playername
a=list(df.playerId)

In [17]:
#creating a dictionary for player Id: playername
b=list(df.playerName)

In [18]:
#dictionary created
dictionary = dict(zip(b,a))

In [19]:
dictionary

{'Gilberto Celestino': 665482,
 'Webster Rivas': 593590,
 'Vladimir Gutierrez': 661269,
 'Eli Morgan': 669212,
 'Alek Manoah': 666201,
 'Owen Miller': 680911,
 'Taylor Walls': 670764,
 'Jose Godoy': 608422,
 'Jean Carlos Mejia': 650496,
 'Luis Barrera': 642456,
 'P.J. Higgins': 664731,
 'Bailey Ober': 641927,
 'Johneshwy Fargas': 641561,
 'Khalil Lee': 666137,
 'Tommy Nance': 667297,
 'Ivan Castillo': 622668,
 'Logan Gilbert': 669302,
 'Jarred Kelenic': 672284,
 'Cody Poteet': 547001,
 'Troy Stokes Jr.': 657011,
 'Trevor Larnach': 663616,
 'Sebastian Rivero': 665861,
 'Nick Gordon': 624503,
 'Patrick Mazeika': 664850,
 'Anthony Bender': 669622,
 'Hunter Owen': 670462,
 'Andy Ibanez': 628451,
 'Daniel Lynch': 663738,
 'Keegan Thompson': 624522,
 'Alec Bettinger': 676424,
 'Lucas Gilbreath': 656458,
 'Wyatt Mills': 670090,
 'Nick Sandlin': 680704,
 'Ben Rortvedt': 666163,
 'Edwin Uceta': 670955,
 'Justin Lawrence': 664875,
 'Jay Flaa': 664852,
 'Hyeon-Jong Yang': 660365,
 'Louis Head': 545343,
 'Zac Lowther': 675912,
 'Aaron Northcraft': 573062,
 'Kent Emanuel': 592288,
 'Jason Vosler': 613564,
 'Corey Ray': 641999,
 'Jose Devers': 672701,
 'Ryan Hendrix': 641682,
 'DJ Peters': 656847,
 'Zack Short': 670097,
 'J.B. Bukauskas': 656266,
 'Sam Hentges': 656529,
 'Nick Maton': 665155,
 'Peter Solomon': 656981,
 'Camilo Doval': 666808,
 'Alex De Goti': 621008,
 'Scott Hurst': 656568,
 'Eduard Bazardo': 660825,
 'Ronnie Dawson': 669008,
 'Justin Steele': 657006,
 'Brent Honeywell Jr.': 641703,
 'Alex Lange': 656638,
 'Alan Trejo': 676701,
 'Josh Palacios': 641943,
 'Luke Raley': 670042,
 'Ty Tice': 676709,
 'Sam Clay': 621348,
 'Cody Wilson': 680963,
 'Kevin Padlo': 656821,
 'Matt Peacock': 676840,
 'Ryan McKenna': 663630,
 'Mac Sceroler': 669135,
 'Akil Baddoo': 668731,
 'Tyler Wells': 669330,
 'Garrett Whitlock': 676477,
 'Jake Brentz': 641394,
 'Zach Pop': 647315,
 'Trevor Stephan': 663986,
 'Luis Oviedo': 665854,
 'Paul Campbell': 669294,
 'Kohei Arihara': 685503,
 'Hirokazu Sawamura': 617228,
 'Ben Bowden': 641386,
 'Jordan Sheffield': 642068,
 'Chris Rodriguez': 669735,
 'Jose Rojas': 670351,
 'Andrew Vaughn': 683734,
 'Jonathan India': 663697,
 'Kyle Isbel': 664728,
 "Ka'ai Tom": 664789,
 'Taylor Trammell': 666211,
 'Tucupita Marcano': 672779,
 'Ha-Seong Kim': 673490,
 'Will Vest': 676684,
 'Chas McCormick': 676801,
 'Brett de Geus': 676969,
 'Ryan Weathers': 677960,
 'Shane McClanahan': 663556,
 'Alex Kirilloff': 666135,
 'Tucker Davidson': 656353,
 'Tommy Doyle': 656382,
 'Jared Oliva': 666931,
 'Patrick Murphy': 641907,
 'Demarcus Evans': 663770,
 'Garrett Crochet': 676979,
 'Garrett Cleavinger': 664076,
 'Bruce Zimmermann': 669145,
 'Zach McKinstry': 656716,
 'Mickey Moniak': 666160,
 'Tanner Houck': 656557,
 'Travis Blankenhorn': 663905,
 'Blake Cederlind': 664977,
 'Rafael Marchan': 665561,
 'Braxton Garrett': 666129,
 'Jonathan Stiever': 680692,
 'Pavin Smith': 656976,
 'Sherten Apostel': 665947,
 'Alejandro Kirk': 672386,
 'Domingo Tapia': 593619,
 'Sam Huff': 669087,
 'Yadiel Hernandez': 628450,
 'Kyle Nelson': 669459,
 'Daz Cameron': 663662,
 'Jose Mujica': 620445,
 'Wyatt Mathisen': 621500,
 'Jorge Ona': 671250,
 'Sergio Alcantara': 642727,
 'Dean Kremer': 665152,
 'Patrick Weigel': 622256,
 'Derek Hill': 656537,
 'Clarke Schmidt': 657376,
 'John King': 667463,
 'Brent Rooker': 667670,
 'Luis Campusano': 669134,
 'Luis Garcia': 472610,
 'Bernardo Flores Jr.': 641576,
 'Justin Topa': 623437,
 'Phil Bickford': 641360,
 'Eli White': 642201,
 "Ke'Bryan Hayes": 663647,
 'Antonio Santos': 665733,
 'Jazz Chisholm Jr.': 665862,
 'Carlos Hernandez': 672578,
 'Robinson Leyer': 622490,
 'Jahmai Jones': 663330,
 'Miguel Yajure': 664337,
 'Deivi Garcia': 665620,
 'Bobby Dalbec': 666915,
 'Ben Braymer': 664069,
 'Estevan Florial': 664314,
 'Mitch White': 669952,
 'Luis Alexander Basabe': 642772,
 'Will Craig': 643269,
 'Riley Smith': 642092,
 'Ian Anderson': 666120,
 'Jonah Heim': 641680,
 'Trevor Rogers': 669432,
 'Brandon Leibrandt': 605335,
 'Brian Navarreto': 640459,
 'Josh Fleming': 676596,
 'Mark Payton': 592622,
 'Wil Crowe': 640444,
 'Triston McKenzie': 663474,
 'Sixto Sanchez': 664350,
 'Aaron Fletcher': 667465,
 'Kyle Cody': 621129,
 'Jesus Sanchez': 660821,
 'Ryan Mountcastle': 663624,
 'Cristian Pache': 665506,
 'JoJo Romero': 668941,
 'Ramon Urias': 602104,
 'Julian Merryweather': 657240,
 'Joey Bart': 663698,
 'Ljay Newsome': 664714,
 'Ryan Jeffers': 680777,
 'Ashton Goudeau': 623485,
 'Dane Dunning': 641540,
 'Drew Rasmussen': 656876,
 'Casey Mize': 663554,
 'Johan Oviedo': 670912,
 'Angel Perdomo': 622780,
 'Tarik Skubal': 669373,
 'Luis Gonzalez': 670768,
 'Nabil Crismatt': 622503,
 'Ricardo Sanchez': 645307,
 'Tyson Miller': 668338,
 'Isaac Paredes': 670623,
 'John Nogowski': 596056,
 'Wes Benjamin': 605138,
 'James Kaprielian': 621076,
 'Rob Kaminsky': 641739,
 'Keibert Ruiz': 660688,
 'Seth Elledge': 676220,
 'Max Schrock': 621011,
 'Lewin Diaz': 650331,
 'Jake Woodford': 663765,
 'Dylan Carlson': 666185,
 'Brandon Waddell': 663399,
 'Keegan Akin': 669211,
 'Kyle Hart': 606996,
 'Jorge Mateo': 622761,
 'Connor Brogdon': 641401,
 'Seth Romero': 656913,
 'Alec Bohm': 664761,
 'Jeremy Beasley': 676886,
 'Ali Sanchez': 645305,
 'Dakota Bacus': 621290,
 'Spencer Howard': 675921,
 'Ryan Castellani': 624418,
 'Zack Burdi': 641420,
 'Daniel Castano': 641447,
 'Albert Abreu': 656061,
 'Nick Mears': 683232,
 'Humberto Mejia': 650668,
 'Jorge Guzman': 660422,
 'Anderson Tejeda': 660731,
 'Sterling Sharp': 643532,
 'Carlos Sanabria': 656004,
 'Eddy Alvarez': 657193,
 'Luis Patino': 672715,
 'Humberto Castellanos': 528748,
 'Monte Harrison': 656509,
 'Mark Mathias': 664029,
 'Jo Adell': 666176,
 'Joey Gerber': 680702,
 'Yermin Mercedes': 606213,
 'Cody Ponce': 664074,
 'Matt Foster': 641582,
 'Franklyn Kilome': 642584,
 'Nick Nelson': 656793,
 'Andrew Young': 670370,
 'Victor Gonzalez': 624647,
 'Kris Bubic': 663460,
 'Nick Madrigal': 663611,
 'Daulton Varsho': 662139,
 'Nick Heath': 670084,
 'Brooks Kriske': 621139,
 'Chadwick Tromp': 644433,
 'Nate Pearson': 663878,
 'Jordan Weems': 607179,
 'Joseph Odom': 641929,
 'David Peterson': 656849,
 'Rony Garcia': 665621,
 'Andre Scrubb': 668687,
 'Nivaldo Rodriguez': 670550,
 'Kyle Funkhouser': 608335,
 'Anthony Castro': 621593,
 'Tejay Antone': 622088,
 'Brandon Bielak': 656232,
 'Beau Burrows': 663366,
 'Tyler Stephenson': 663886,
 'Vimael Machin': 605353,
 'Taylor Jones': 622100,
 'Jake Cronenworth': 630105,
 'Thomas Hatch': 641672,
 'Jordan Holloway': 656548,
 'Cam Hill': 657611,
 'JT Brubaker': 664141,
 'Brandon Bailey': 669064,
 'Kodi Whitley': 676831,
 'Shun Yamaguchi': 685493,
 'Kyle Finnegan': 640448,
 'Taylor Widener': 642203,
 'Edward Olivares': 658668,
 'Nick Neidert': 663734,
 'Brady Singer': 663903,
 'Cristian Javier': 664299,
 'Aaron Whitefield': 664334,
 'Daniel Johnson': 669288,
 'Santiago Espinal': 669289,
 'Jimmy Lambert': 669424,
 'Caleb Baragar': 670056,
 'Alex Vesia': 681911,
 'Kwang Hyun Kim': 547942,
 'Jose Marmolejos': 592530,
 'Blake Taylor': 642130,
 'J.P. Feyereisen': 656420,
 'Ryan Thompson': 657044,
 'Evan White': 657108,
 'Yoshi Tsutsugo': 660294,
 'Enoli Paredes': 660600,
 'Jonathan Arauz': 660620,
 'William Contreras': 661388,
 'Anthony Misiewicz': 664948,
 'Leody Taveras': 665750,
 'Ramon Rosso': 665759,
 'Andres Gimenez': 665926,
 'Yohan Ramirez': 670990,
 'Luis Robert': 673357,
 'Shogo Akiyama': 673451,
 'Codi Heuer': 676051,
 'Tyler Zuber': 676604,
 'Joe McCarthy': 663411,
 'Dany Jimenez': 666204,
 'Michael King': 650633,
 'Deivy Grullon': 620453,
 'Jorge Alcala': 660896,
 'Enderson Franco': 575070,
 'Tres Barrera': 668663,
 'James Karinchak': 675916,
 'Art Warren': 605521,
 'Justin Dunn': 643290,
 'Johnny Davis': 643275,
 'Jesus Luzardo': 666200,
 'Donovan Walton': 622268,
 'Kyle Lewis': 641786,
 'Nico Hoerner': 663538,
 'Danny Hultzen': 543343,
 'James Marvel': 621086,
 'Tyrone Taylor': 621438,
 'Anthony Kay': 641743,
 'Cole Sulser': 642121,
 'Brian Moran': 572383,
 'Erick Mejia': 625510,
 'Gabe Speier': 642100,
 'Kean Wong': 642221,
 'Tyler Heineman': 623168,
 'Seth Mejias-Brean': 623180,
 'Ian Miller': 641878,
 'Jaylin Davis': 664041,
 'Sam Haggerty': 664059,
 'Ryan McBroom': 643436,
 'T.J. Zeuch': 643615,
 'Danny Mendick': 664901,
 'Ronald Bolanos': 671790,
 'Bryan Garcia': 650530,
 'Gavin Lux': 666158,
 'Brusdar Graterol': 660813,
 'David Bednar': 670280,
 'Tyler Rogers': 643511,
 'Sam Hilliard': 656541,
 'Rico Garcia': 670329,
 'Seth Brown': 664913,
 'Willi Castro': 650489,
 'Abraham Toro': 647351,
 'Joel Payamps': 606303,
 'A.J. Puk': 640462,
 'Jake Fraley': 641584,
 'Eric Yardley': 642233,
 'Jonathan Hernandez': 642546,
 'Miguel Del Pozo': 600887,
 'Brock Burke': 656271,
 'Nick Solak': 669256,
 'Taylor Guilbeau': 607555,
 'Hunter Harvey': 640451,
 'Logan Webb': 657277,
 'Joel Kuhnel': 669270,
 'Randy Arozarena': 668227,
 'Chandler Shepherd': 605469,
 'Dom Nunez': 624513,
 'Adonis Rosa': 650738,
 'Brady Lail': 621078,
 'Josh Rojas': 668942,
 'Junior Fernandez': 658551,
 'John Schreiber': 670167,
 'Randy Dobnak': 677976,
 "Brian O'Grady": 657434,
 'Devin Williams': 642207,
 'Nick Dini': 664926,
 'Isan Diaz': 656371,
 'Kevin Ginkel': 656464,
 'Patrick Sandoval': 663776,
 'Robert Dugger': 667498,
 'Yennsy Diaz': 660546,
 'Emmanuel Clase': 661403,
 'Kyle Keller': 664918,
 'Scott Heineman': 595981,
 'Reggie McClain': 596035,
 'Travis Demeritte': 641513,
 'Zac Grotz': 665093,
 'Dustin May': 669160,
 'Sam Selman': 572125,
 'Trent Grisham': 663757,
 'Bryan Abreu': 650556,
 'Jake Rogers': 668670,
 'Dillon Tate': 622253,
 'Bo Bichette': 666182,
 'Jose Rodriguez': 642578,
 'Ryan Court': 606956,
 'Jeremy Walker': 668683,
 'Josh Staumont': 622251,
 'Tim Lopes': 621005,
 'Cody Stashak': 664054,
 'Michel Baez': 673258,
 'Zach Green': 608339,
 'Conner Menez': 669214,
 'Adrian Morejon': 670970,
 'Luis Escobar': 650813,
 'Bubba Starling': 605490,
 'Andres Munoz': 662253,
 'Ian Gibaut': 664139,
 'Jimmy Herget': 623474,
 'Mauricio Dubon': 643289,
 'Pedro Payano': 622797,
 'Robel Garcia': 596825,
 'Tyler Alexander': 641302,
 'Matt Thaiss': 642136,
 'Dylan Cease': 656302,
 'Jose Urquidy': 664353,
 'Trevor Kelley': 665001,
 'Thomas Eshelman': 664045,
 'Lewis Thorpe': 626929,
 'Chris Mazza': 607391,
 'Brendan McKay': 656713,
 'Yu Chang': 644374,
 'LaMonte Wade Jr': 664774,
 'Cy Sneed': 605482,
 'Edwin Rios': 621458,
 'Alex Young': 622065,
 'Tony Gonsolin': 664062,
 'Locke St. John': 657766,
 'Bobby Bradley': 656252,
 'Mike Brosseau': 670712,
 'Domingo Leyba': 642736,
 'Aaron Civale': 650644,
 'Humberto Arteaga': 600858,
 'Josh Sborz': 622250,
 'Adbert Alzolay': 640470,
 'Zac Gallen': 668678,
 'Zack Collins': 641470,
 'Sean Poppen': 664092,
 'Stephen Nogosek': 668665,
 'Logan Allen': 663531,
 'Rangel Ravelo': 592660,
 'Austin Nola': 543592,
 'Huascar Ynoa': 660623,
 'Dario Agrazal': 642607,
 'Rogelio Armenteros': 660494,
 'Jordan Romano': 605447,
 'Jordan Yamamoto': 657141,
 'Phillip Diehl': 670426,
 'Pete Fairbanks': 664126,
 'Yordan Alvarez': 670541,
 'Phillips Valdez': 570488,
 'Ryan Eades': 592280,
 'Tayler Scott': 605463,
 'Colin Poche': 621363,
 'Joe Palumbo': 643478,
 'Tommy Edman': 669242,
 'Mike Shawaryn': 642067,
 'Peter Lambert': 663567,
 'Adam Haseley': 656514,
 'Jose Suarez': 660761,
 'Andrew Knizner': 668800,
 'Jesus Tinoco': 622786,
 'Genesis Cabrera': 650893,
 'Josh Taylor': 657031,
 'Garrett Stubbs': 596117,
 'Devin Smeltzer': 656970,
 'Zach Plesac': 668676,
 'Will Smith': 519293,
 'Jack Mayfield': 608686,
 'Jacob Waguespack': 621097,
 'Mitch Keller': 656605,
 'James Bourque': 630263,
 'Sam Coonrod': 656322,
 'JD Hammer': 670456,
 'Mike Yastrzemski': 573262,
 'Josh D. Smith': 605479,
 'Seby Zavala': 664874,
 'Kevin Cron': 605196,
 'Cavan Biggio': 624415,
 'Josh Naylor': 647304,
 'David McKay': 641853,
 'Sheldon Neuse': 641914,
 'Kyle Garlick': 664247,
 'Sean Murphy': 669221,
 'Luis Arraez': 650333,
 'Geoff Hartlieb': 664129,
 'Brendan Rodgers': 663898,
 'Shaun Anderson': 641312,
 'Austin Riley': 663586,
 'Jared Walsh': 665120,
 'Oscar Mercado': 640458,
 'Keston Hiura': 669374,
 'Nicky Lopez': 670032,
 'Parker Markel': 571917,
 'Cole Irvin': 608344,
 'Anthony Bemboom': 621532,
 'Corbin Martin': 656686,
 'Nick Ramirez': 598286,
 'Harold Ramirez': 623912,
 'Gregory Soto': 642397,
 'Shed Long Jr.': 643418,
 'Austin Allen': 664119,
 'Montana DuRapau': 657566,
 'Eduardo Jimenez': 621592,
 'Edgar Garcia': 658305,
 'Josh VanMeter': 642165,
 'Skye Bolt': 621450,
 'Nick Senzel': 669222,
 'Cal Quantrill': 615698,
 'Matt Beaty': 607461,
 'Griffin Canning': 656288,
 'Nate Lowe': 663993,
 'Kelvin Gutierrez': 642721,
 'Ty France': 664034,
 'Vladimir Guerrero Jr.': 665489,
 'Carter Kieboom': 666198,
 'Matt Ramsey': 543677,
 'Taylor Hearn': 621368,
 'Luis Rengifo': 650859,
 'Jose Quijada': 650671,
 'Darwinzon Hernandez': 650382,
 'Wei-Chieh Huang': 658791,
 'Travis Lakins Sr.': 664042,
 'Thairo Estrada': 642731,
 'Branden Kline': 571858,
 'Michael Chavis': 656308,
 'Cole Tucker': 657061,
 'Taylor Clarke': 664199,
 'Bryan Reynolds': 668804,
 'Brett Martin': 656685,
 'Mike Ford': 645801,
 'Lane Thomas': 657041,
 'Jacob Webb': 657097,
 'Ryan Helsley': 664854,
 'R.J. Alaniz': 595798,
 'Gerardo Reyes': 622103,
 'Erik Swanson': 657024,
 'Pedro Avila': 658648,
 'Joe Harvey': 642840,
 'Yonathan Daza': 602074,
 'Richard Lovelady': 663992,
 'Alex Jackson': 656577,
 'Jason Martin': 641829,
 'Joshua Fuentes': 658069,
 'Matt Wotherspoon': 642226,
 'Merrill Kelly': 518876,
 'Jon Duplantier': 641541,
 'Chris Ellis': 595939,
 'Ryne Harper': 607560,
 'Kyle Zimmer': 622092,
 'Trent Thornton': 663423,
 'Chris Paddack': 663978,
 'Elvis Luciano': 672773,
 'Jake Noll': 669738,
 'Nick Margevicius': 676606,
 'Reed Garrett': 657585,
 'Travis Bergen': 664157,
 'Eric Stamets': 608715,
 'Kyle Bird': 613317,
 'Richie Martin': 621006,
 'Nick Anderson': 623433,
 'Drew Jackson': 623515,
 'Pete Alonso': 624413,
 'Frank Schwindel': 643524,
 'Eloy Jimenez': 650391,
 'Connor Joe': 656582,
 'Kyle Dowdy': 664871,
 'Fernando Tatis Jr.': 665487,
 'Yusei Kikuchi': 579328,
 'Brandon Brennan': 592165,
 'Braden Bishop': 623323,
 'Dylan Moore': 664238,
 'Jon Berti': 542932,
 'John Means': 607644,
 'Harold Castro': 605612,
 'Edmundo Sosa': 624641,
 'Sherman Johnson': 582473,
 'Justus Sheffield': 656954,
 'Matt Hall': 664180,
 'Myles Straw': 664702,
 'Spencer Turnbull': 605513,
 'Brad Wieck': 623364,
 'DJ Stewart': 621466,
 'Nick Burdi': 595897,
 'DJ Johnson': 597113,
 'Christin Stewart': 621514,
 'Yoan Lopez': 661255,
 'Joe Hudson': 621529,
 'Abiatal Avelino': 623214,
 'Luis Ortiz': 656814,
 'Reese McGuire': 624512,
 'Kevin Kramer': 596012,
 'Jonathan Davis': 641505,
 'Kyle McGowin': 641851,
 'CD Pelham': 641962,
 'Rowdy Tellez': 642133,
 'Dean Deetz': 657209,
 'Gabriel Guerrero': 602115,
 'Eric Hanhold': 621098,
 'Kyle Wright': 657140,
 'Nick Ciuffo': 624419,
 'Ryan Cordell': 641477,
 'Blake Trahan': 664167,
 'Stephen Tarpley': 605501,
 'Eric Haase': 606992,
 'Caleb Frare': 621350,
 'Pablo Reyes': 622569,
 'Andrew Velazquez': 623205,
 'Meibrys Viloria': 650619,
 'Jeff Brigham': 656257,
 'Austen Williams': 657117,
 'Connor Sadzeck': 592712,
 'Taylor Guerrieri': 605260,
 'Beau Taylor': 607333,
 'Andrew Vasquez': 607755,
 'Jose Manuel Fernandez': 622774,
 'Josh James': 657624,
 'Rowan Wick': 592858,
 'Aramis Garcia': 605244,
 'Chris Shaw': 622046,
 'Ian Hamilton': 641656,
 'Dawel Lugo': 608475,
 'Josh Rogers': 642028,
 'Luis Urias': 649966,
 'Murphy Smith': 573166,
 'Ryan Burr': 621114,
 'Michael Kopech': 656629,
 'Framber Valdez': 664285,
 'Jake Newberry': 623470,
 'Stephen Gonsalves': 624427,
 'Bryse Wilson': 669060,
 'Justin Shafer': 596101,
 'Aristides Aquino': 606157,
 'Daniel Zamora': 623354,
 'Osmer Morales': 591672,
 'Kevin Newman': 621028,
 'Ty Buttrey': 621142,
 'Austin Dean': 621573,
 'Taylor Ward': 621493,
 'Danny Jansen': 643376,
 'Sean Reid-Foley': 656887,
 'Touki Toussaint': 657053,
 'Patrick Wisdom': 621550,
 'Kohl Stewart': 640464,
 'Thomas Pannone': 623381,
 'Cedric Mullins': 656775,
 'Jacob Nix': 656798,
 'Chad Sobotka': 656977,
 'Adam McCreery': 607030,
 'Wes Parsons': 641149,
 'Brett Kennedy': 664028,
 'Adolis Garcia': 666969,
 'Williams Jerez': 605301,
 'Trey Wingenter': 622259,
 'Brandon Lowe': 664040,
 'Jesus Reyes': 660875,
 'Chance Adams': 664856,
 'Ramon Laureano': 657656,
 'Jimmy Cordero': 622772,
 'Cody Carroll': 606944,
 'Alex McRae': 656725,
 'Isaac Galloway': 543194,
 'Jeffrey Springs': 605488,
 "Ryan O'Hearn": 656811,
 'Kolby Allard': 663465,
 'Dakota Hudson': 641712,
 'Francisco Arcia': 516472,
 'Michael Perez': 605421,
 'Ranger Suarez': 624133,
 'Jeff McNeil': 643446,
 'Daniel Ponce de Leon': 594965,
 'Garrett Hampson': 641658,
 'Justin Williams': 642211,
 'Austin Voth': 608723,
 'Matt Festa': 670036,
 'Jeremy Bleich': 542946,
 'James Norwood': 656803,
 'Cionel Perez': 672335,
 'Drew Gagnon': 543193,
 'Enyel De Los Santos': 660853,
 'Corbin Burnes': 669203,
 'Ray Black': 605143,
 'Steven Duggar': 621453,
 'Kyle Tucker': 663656,
 'Evan Phillips': 623465,
 'Joey Krehbiel': 607216,
 'Nate Orf': 644337,
 'Tanner Anderson': 664196,
 'Willians Astudillo': 553902,
 'Pablo Lopez': 641154,
 'Paul Fry': 643316,
 'Ryan Meisinger': 664682,
 'Ryan Borucki': 621366,
 'Duane Underwood Jr.': 621249,
 'Tyler Bashlor': 641341,
 'Robert Stock': 476594,
 'Heath Fillmyer': 641571,
 'Kevin Kaczmarski': 664842,
 'Drew Smith': 622098,
 'Yency Almonte': 622075,
 'Stevie Wilkerson': 592859,
 'Austin Davis': 656354,
 'Brett Graves': 605255,
 'Jake Jewell': 657228,
 'Jose Trevino': 624431,
 'Jonathan Loaisiga': 642528,
 'Yefry Ramirez': 606162,
 'David Fletcher': 664058,
 'Sam Howard': 607572,
 'Jerry Vasto': 657786,
 'Jose Miguel Fernandez': 628336,
 'Jake Bauers': 641343,
 'Jalen Beeks': 656222,
 'Ben Meyer': 656738,
 'Nick Martini': 605361,
 'Diego Castillo': 650895,
 'Caleb Ferguson': 657571,
 'Zack Littell': 641793,
 'Austin Wynns': 642851,
 'Sandy Baez': 622783,
 'Jefry Rodriguez': 622446,
 'Austin Gomber': 596295,
 'Jose Castillo': 620454,
 'Walker Lockett': 621141,
 'Dylan Cozens': 622226,
 'Dennis Santana': 642701,
 'Ronny Rodriguez': 500135,
 'Shane Bieber': 669456,
 'Mitch Walding': 605520,
 'Tim Peterson': 623402,
 'Dereck Rodriguez': 605446,
 'Jaime Schultz': 621289,
 'Matt Skole': 605474,
 'Dustin Peterson': 640460,
 'Alfredo Gonzalez': 554054,
 'Jose Briceno': 593993,
 'John Andreoli': 607430,
 'Brandon Dixon': 641525,
 'Willy Adames': 642715,
 'Jake Cave': 595909,
 'Ariel Jurado': 642558,
 'Austin Meadows': 640457,
 'Michael Hermosillo': 641684,
 'Juan Soto': 665742,
 'Franmil Reyes': 614177,
 'Brandon Mann': 448167,
 'Freddy Peralta': 642547,
 'David Hess': 605276,
 'Luis Guillorme': 641645,
 'Elieser Hernandez': 622694,
 'Justin Hancock': 606995,
 'Seranthony Dominguez': 622554,
 'P.J. Conlon': 664869,
 'Grayson Greiner': 606988,
 'Jason Adam': 592094,
 'Javy Guerra': 457915,
 'Fernando Romero': 622864,
 'Wander Suero': 593833,
 'Mike Soroka': 647336,
 'Scott Barlow': 605130,
 'Nick Kingham': 592468,
 'Jesmuel Valentin': 621044,
 'D.J. Snelten': 592769,
 'Trevor Oaks': 656805,
 'Rosell Herrera': 594011,
 'Daniel Palka': 594953,
 'Corey Oswalt': 621261,
 'Eric Stout': 657770,
 'Ronald Acuna Jr.': 660670,
 'Eric Lauer': 641778,
 'Justin Anderson': 605121,
 'Harrison Musgrave': 643466,
 'Noel Cuevas': 571595,
 'Gleyber Torres': 650402,
 'Jesse Biddle': 592145,
 'David Bote': 623520,
 'Mike Gerber': 595222,
 'Lourdes Gurriel Jr.': 666971,
 "Tyler O'Neill": 641933,
 'Merandy Gonzalez': 642571,
 'Gerson Bautista': 639373,
 'Lou Trivino': 642152,
 'Jacob Nottingham': 641924,
 'Johnny Field': 608654,
 'Ronald Guzman': 608597,
 'Engelb Vielma': 622713,
 'Zack Weiss': 592848,
 'Colten Brewer': 605155,
 'Andrew Suarez': 605498,
 'Jaime Barria': 642545,
 'Tyler Beede': 595881,
 'Alex Blandino': 607468,
 'Isiah Kiner-Falefa': 643396,
 'Tanner Rainey': 663432,
 'Tyler Kinley': 641755,
 'Clay Holmes': 605280,
 'Trevor Richards': 670950,
 'Marcus Walden': 519393,

In [20]:
standings_df

,teamName,gameDate,divisionRank,leagueRank,wildCardRank,xWinLossPct
0,Chicago Cubs,2018-03-29,1,3,3,0.0
1,Miami Marlins,2018-03-29,4,12,12,0.0
2,New York Mets,2018-03-29,2,5,5,1.0
3,Texas Rangers,2018-03-29,5,14,13,0.0
4,Atlanta Braves,2018-03-29,1,2,2,0.0
...,...,...,...,...,...,...
16455,St. Louis Cardinals,2021-04-30,2,6,4,0.6
16456,Arizona Diamondbacks,2021-04-30,4,5,3,0.833
16457,San Francisco Giants,2021-04-30,1,2,NaN,0.667
16458,Washington Nationals,2021-04-30,3,11,8,0.667
16459,Philadelphia Phillies,2021-04-30,1,7,NaN,0.571

In [21]:
target_df

,engagementMetricsDate,playerId,target1,target2,target3,target4
0,2018-01-02,628317,0.011167070542384616,4.474708171206226,0.005167729742499409,5.735294117647059
1,2018-01-02,547989,0.04299322158818077,5.593385214007783,0.04503307347035199,2.794117647058824
2,2018-01-02,519317,0.9743269048230578,56.17704280155642,13.693745570517363,64.16666666666667
3,2018-01-02,607625,0.0067002423254307695,2.6750972762645913,0.005167729742499409,1.8627450980392157
4,2018-01-02,592547,0.0011167070542384616,0.632295719844358,0.002952988424285377,0.9313725490196079
...,...,...,...,...,...,...
4249776,2021-05-01,451661,0,0.013314249575608294,0,0.6259246614316604
4249777,2021-05-01,519301,0.00013148828965292353,0.0033285623939020735,0,0.21622851940366453
4249778,2021-05-01,527055,0,0.019971374363412443,0,0.27313076135199726
4249779,2021-05-01,543484,0.00013148828965292353,0.056585560696335246,0,1.0242403550699897
4249780,2021-05-01,605525,0.00013148828965292353,0.49928435908531105,0,0.3869352452486628

In [22]:
#data cleaning the date 
target_df = target_df.rename(columns = {'engagementMetricsDate': 'gameDate'}, inplace = False)

In [23]:
#taking only the first 7 digits of the target column
target_df.target1= target_df.target1.map(lambda x: x[0:6])
target_df.target2= target_df.target2.map(lambda x: x[0:6])
target_df.target3= target_df.target3.map(lambda x: x[0:6])
target_df.target4= target_df.target4.map(lambda x: x[0:6])

In [24]:
# workframe=target_df.T

In [25]:
df3=pd.read_csv('awards.csv')
df3.drop(['Unnamed: 0'], axis=1, inplace=True)

In [26]:
df3

,awardId,awardName,awardDate,awardSeason,playerId,playerName,awardPlayerTeamId
0,VWLCPOY,VWL Comeback Player of the Year,2018-01-15,2017,150119,Freddy Garcia,699
1,VWLPOY,VWL Pitcher of the Year,2018-01-15,2017,446861,Guillermo Moscoso,699
2,VWLMOY,VWL Manager of the Year,2018-01-15,2017,492527,Mike Rojas,695
3,VWLRLOY,VWL Reliever of the Year,2018-01-15,2017,519246,Andres Santiago,694
4,VWLOPOY,VWL Offensive Player of the Year,2018-01-15,2017,543874,Jose Vargas,699
...,...,...,...,...,...,...,...
6203,NLPOM,NL Player of the Month,2021-04-30,2021,660670,Ronald Acuna Jr.,144
6204,ALRRELMON,AL Reliever of the Month,2021-04-30,2021,598264,Matt Barnes,111
6205,ALPOM,AL Player of the Month,2021-04-30,2021,621439,Byron Buxton,142
6206,ALROM,AL Rookie of the Month,2021-04-30,2021,606213,Yermin Mercedes,145
6207,ALPITOM,AL Pitcher of the Month,2021-04-30,2021,543037,Gerrit Cole,147

In [27]:

work= pd.merge(target_df, df3, how='outer', on= ['playerId'])

In [28]:
offense_df

          gameDate               teamName      playerName atBats  rbi homeRuns
0       2018-03-29    Los Angeles Dodgers   Austin Barnes    0.0  0.0      0.0
1       2018-03-29         Tampa Bay Rays    Mallex Smith    0.0  0.0      0.0
2       2018-03-29  Philadelphia Phillies  Odubel Herrera    0.0  0.0      0.0
3       2018-03-29     Los Angeles Angels     Jefry Marte    0.0  0.0      0.0
4       2018-03-29     Kansas City Royals   Paulo Orlando    0.0  0.0      0.0
...            ...                    ...             ...    ...  ...      ...
185673  2021-04-30   San Francisco Giants      Logan Webb    2.0  0.0      0.0
185674  2021-04-30      Milwaukee Brewers  Freddy Peralta    2.0  0.0      0.0
185675  2021-04-30       Colorado Rockies        Jon Gray    2.0  0.0      0.0
185676  2021-04-30       San Diego Padres      Yu Darvish    2.0  0.0      0.0
185680  2021-04-30          Miami Marlins     Pablo Lopez    3.0  0.0      0.0

[154290 rows x 6 columns]

In [29]:
offense_df.playerName.replace(dictionary, inplace=True)

In [30]:
offense_df.rename(columns={'playerName': 'playerId'}, inplace=True)

In [31]:
work.gameDate.replace('engagementMetricsDate', np.nan).dropna(axis=0, inplace=True)

In [32]:
work.dropna(axis=0, inplace=True)

In [33]:
homeruns_df

          gameDate playerId      playerName  homeRuns       date
67      2018-03-29   607680    Kevin Pillar       1.0 2018-03-29
70      2018-03-29   443558     Nelson Cruz       1.0 2018-03-29
79      2018-03-29   518934     DJ LeMahieu       1.0 2018-03-29
94      2018-03-29   446263      Lucas Duda       1.0 2018-03-29
99      2018-03-29   605412       Joe Panik       1.0 2018-03-29
...            ...      ...             ...       ...        ...
185534  2021-04-30   571745   Mitch Haniger       1.0 2021-04-30
185535  2021-04-30   666182     Bo Bichette       1.0 2021-04-30
185537  2021-04-30   545341  Randal Grichuk       1.0 2021-04-30
185543  2021-04-30   543305     Aaron Hicks       1.0 2021-04-30
185552  2021-04-30   608324    Alex Bregman       1.0 2021-04-30

[14840 rows x 5 columns]

In [43]:
work2= pd.merge(work, homeruns_df, how='inner', on= ['playerId'])

In [44]:
work2.rename(columns={'gameDate_x': 'gameDate'}, inplace=True)

In [45]:
frames=[work2, homeruns_df]
work3=pd.concat(frames, join='outer', keys= ['gameDate'])

In [46]:
work3.isna().sum()

gameDate             0
playerId             0
target1              0
target2              0
target3              0
target4              0
awardId              0
awardName            0
awardDate            0
awardSeason          0
playerName_x         0
awardPlayerTeamId    0
gameDate_y           0
playerName_y         0
homeRuns             0
date                 0
dtype: int64

In [47]:
work3.drop(['playerName_x', 'playerName_y'], axis=1, inplace=True)

In [48]:
work3.drop(['gameDate_y'], axis=1, inplace=True)

In [49]:
work3[['gameDate', 'date']]

                     gameDate       date
gameDate 0         2018-01-02 2018-03-29
         1         2018-01-02 2018-04-04
         2         2018-01-02 2018-04-10
         3         2018-01-02 2018-04-16
         4         2018-01-02 2018-04-23
...                       ...        ...
         95751994  2021-05-01 2020-09-04
         95751995  2021-05-01 2020-09-25
         95751996  2021-05-01 2021-04-07
         95751997  2021-05-01 2021-04-26
         95751998  2021-05-01 2021-04-30

[95751999 rows x 2 columns]

In [50]:
#loading XGBoost
import xgboost as xgb

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
X= work3.drop(columns=['target1', 'target2', 'target3', 'target4'], axis=1)

y= work3['target1']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=3)

In [53]:
from sklearn.model_selection import GridSearchCV

In [57]:
#instantiating xgboost 
xg_clf = xgb.XGBClassifier(booster = 'gblinear', verbosity=3, validate_parameters=True, n_jobs=-1)

In [58]:
#creating a param grid for Gridsearch
xg_clf= xgb.XGBClassifier()
param_grid = {
    'eta': [0.1, .25, .05],
    'feature_selector': ['cyclic', 'thrifty', 'greedy', 'shuffle'],
    'reg_lambda':[.5,1.0, 5, 10],
    'reg_alpha':[.5, 1, 5, 10, .25]
    }

In [63]:
#gridsearch with XGBoost
grid_clf = GridSearchCV(xg_clf, param_grid, cv=3, scoring='neg_mean_squared_error', n_jobs=-1)

In [ ]:
grid_clf.fit(X_train, y_train)

/Users/jeffreyng/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
/Users/jeffreyng/opt/anaconda3/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py:688: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

In [ ]:
y_pred=grid_clf.predict(X_test)

In [ ]:
workdf.isna().sum()

In [ ]:
workdf.target1.dropna(axis=0, inplace=False)

In [ ]:
workdf.target1.replace('target', np.nan, inplace=True)

In [ ]:
workdf.target1.dropna(axis=0, inplace=True)

In [ ]:
workdf.target2.replace('target', np.nan, inplace=True)
workdf.target3.replace('target', np.nan, inplace=True)
workdf.target4.replace('target', np.nan, inplace=True)

In [ ]:
workdf.target2.dropna(axis=0, inplace=True)
workdf.target3.dropna(axis=0, inplace=True)
workdf.target4.dropna(axis=0, inplace=True)

In [ ]:
workdf.isna().sum()